#!/usr/bin/env python3
"""Record the playground presets' verdicts through the real gateway app.

The hosted (GitHub Pages) playground has no gateway; its presets fall back
to these committed recordings — generated by the SAME engine the live page
calls, keyed by the canonical JSON of the exact request body the page
builds (preset arrays are extracted from the page itself by
scripts/playground_presets_dump.js, so there is one source of truth).

Deterministic: no clock, no randomness in any preset verdict; the test
regenerates and byte-compares. Usage: playground_recorded.py [--stdout]
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))


def canonical(body: dict) -> str:
    return json.dumps(body, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=False)


def main() -> int:
    presets = json.loads(subprocess.run(
        ["node", str(REPO / "scripts" / "playground_presets_dump.js")],
        capture_output=True, text=True, timeout=60, check=True,
    ).stdout)

    from fastapi.testclient import TestClient

    from attending.gateway import create_app
    client = TestClient(create_app())

    recorded: dict[str, dict] = {}
    for p in presets:
        resp = client.post(p["path"], json=p["body"])
        key = p["path"] + "|" + canonical(p["body"])
        recorded[key] = {"label": p["label"], "status": resp.status_code,
                         "json": resp.json()}
    out = {
        "_note": ("Recorded preset verdicts for the hosted playground — "
                  "generated offline by the same engine the live gateway "
                  "runs (scripts/playground_recorded.py). Synthetic data "
                  "only. Custom input still requires the local gateway."),
        "recorded": recorded,
    }
    text = json.dumps(out, indent=1, ensure_ascii=False, sort_keys=True) + "\n"
    if "--stdout" in sys.argv:
        sys.stdout.write(text)
    else:
        (REPO / "web" / "playground_recorded.json").write_text(text)
        print(f"wrote web/playground_recorded.json "
              f"({len(recorded)} preset verdicts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
